ci/cd:
- changed-files:
  - any-glob-to-any-file: ['.github/**']
- head-branch: ['^cicd']

code:
- changed-files:
  - any-glob-to-any-file: ['hooks/**', '{{cookiecutter.project_name}}/**']

infrastructure:
- changed-files:
  - any-glob-to-any-file: ['infrastructure/**', 'infra/**', 'terraform/**']

documentation:
- changed-files:
  - any-glob-to-any-file: ['docs/**', '.*.md']

enhancement:
- head-branch: ['^feat']

bug:
- head-branch: ['^fix']
