#!/usr/bin/env python3

import os
import sys
import types


COMMANDS = types.MappingProxyType(
    {"linux": "open", "win32": "cmd /c start", "cygwin": "cygstart", "darwin": "open"},
)


def run(path: str) -> None:
    """Run the given path in the default application."""
    command = COMMANDS.get(sys.platform, "open")
    os.system(f"{command} {path}")


if __name__ == "__main__":
    run(sys.argv[-1])
