# For more cool stuff to enrich your docs check out:
# https://squidfunk.github.io/mkdocs-material/reference/
# https://facelessuser.github.io/pymdown-extensions/
site_name: python-project-skeleton
site_description: A cookiecutter template for python projects.
site_author: "Marco Henriques <marco.martins.henriques@gmail.com>"

repo_url: https://github.com/marcohenriques/python-project-skeleton
edit_uri: ""

theme:
  name: material
  favicon: images/favicon.svg
  logo: images/logo.svg
  icon:
    repo: material/github
  static_templates:
    - 404.html
  feature:
    - navigation.tabs
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  hljs_languages:
    - yaml

markdown_extensions:
  - toc:
      permalink: true
  - smarty
  - extra
  - admonition
  - codehilite
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

extra:
  version:
    provider: mike

plugins:
  - search
  - mkdocstrings

nav:
  - python-project-skeleton: index.md
  - Requirements: requirements.md
  - Quickstart: quickstart.md
  - Rendered template:
    - Formatters: tools_included/formatters.md
    - Linters: tools_included/linters.md
    - pre-commit: tools_included/pre-commit.md
    - Tests: tools_included/tests.md
    - Documentation: tools_included/documentation.md
    - Logging: tools_included/logging.md
    - Makefile: tools_included/makefile.md
    - Poetry: tools_included/poetry.md
    - Docker: tools_included/docker.md
    - Github Actions: tools_included/github_actions.md
    - IDE Settings: tools_included/ide_settings.md
  - Release Notes: changelog.md
