[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "python-project-skeleton"
version = "0.1.0"
description = "{{cookiecutter.project_short_description}}"
authors = ["Marco Henriques <marco.martins.henriques@gmail.com>"]
readme = "README.md"
repository = ""
keywords = []
maintainers = []
license = ""
homepage = ""
documentation = ""

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
# Documentation
mkdocs = "*"
mkdocs-material = "*"
mkdocstrings = {extras = ["python"], version = "*"}
pygments = "*"
pymdown-extensions = "*"
