# For more cool stuff to enrich your docs check out:
# https://squidfunk.github.io/mkdocs-material/reference/
# https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippets-notation
site_name: {{cookiecutter.project_name}}
site_description: {{cookiecutter.project_short_description}}
site_author: {{cookiecutter.author_name}}

repo_url: https://github.com/{{ cookiecutter.github_username_or_org_name }}/{{ cookiecutter.project_name }}
edit_uri: ""

theme:
  name: material
  custom_dir: docs/theme
  favicon: images/favicon.svg
  logo: images/logo.svg
  icon:
    repo: material/github
  static_templates:
    - 404.html
  feature:
    - navigation.tabs
    - content.code.copy
    - content.action.edit
    - content.action.view
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  hljs_languages:
    - yaml

markdown_extensions:
  - toc:
      permalink: true
  - smarty
  - extra
  - admonition
  - codehilite
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

extra:
  version:
    provider: mike

plugins:
  - search
  - autorefs
  - mkdocstrings
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mike:
      alias_type: symlink
      canonical_version: latest


nav:
  - {{cookiecutter.project_name}}: index.md
  - Contributing: contributing.md
  - Code Reference:
    - Settings: reference/settings.md
    - Constants: reference/constants.md
    - Exceptions: reference/exceptions.md
