name: CI

on:
  workflow_call:
  pull_request:
    branches:
      - main
      - master
  workflow_call:

# cancel in progress workflow:
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: {% raw %}${{ github.workflow }}-${{ github.head_ref || github.run_id }}{% endraw %}
  cancel-in-progress: true

jobs:
  ci:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python {{ cookiecutter.python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: "{{ cookiecutter.python_version }}"

    - name: Get full Python version
      id: full-python-version
      run: echo version=$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))") >> $GITHUB_OUTPUT

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: {{cookiecutter.package_name}}
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Set up cache
      uses: actions/cache@v3
      id: cache
      with:
        path: .venv
        key: venv-{% raw %}${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}{% endraw %}

    - name: Ensure cache is healthy
      if: steps.cache.outputs.cache-hit == 'true'
      run: timeout 10s poetry run pip --version || rm -rf .venv

    - name: Install dependencies
      run: |
        poetry run pip install -U pip
        poetry install --with dev,tests

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0

    - name: Run tests
      run: |
        make test
