name: CICD
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run-test:
        description: run tests
        required: false
        type: boolean
        default: true

{% raw %}jobs:
  run-ci-tests:
    uses: ./.github/workflows/ci.yaml
    if: github.event_name != 'workflow_dispatch' || inputs.run-test{% endraw %}
{% if cookiecutter.include_docker == "yes" %}
  {% raw %}build-docker-dev:
    uses: ./.github/workflows/build_docker.yaml
    permissions:
      id-token: write
      contents: read
    needs:
      - run-ci-tests
    if: |
      contains(fromJson('["success", "skipped"]'), needs.run-ci-tests.result)
      && always()
    with:
      image-name:  {% endraw %}{{cookiecutter.project_name.lower()}}{% raw %}
      image-tag: ${{ github.sha }}
      push-image: ${{ (github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')) }}
      push-latest-tag: true

  build-docker-prod:
    uses: ./.github/workflows/build_docker.yaml
    permissions:
      id-token: write
      contents: read
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main')
      && contains(fromJson('["success", "skipped"]'), needs.run-ci-tests.result)
      && always()
    needs:
      - run-ci-tests
    with:
      image-name:  {% endraw %}{{cookiecutter.project_name.lower()}}{% raw %}
      image-tag: ${{ github.sha }}
      push-image: true
      push-latest-tag: true{% endraw %}
{% endif -%}
