name: CICD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  BASE_IMAGE_NAME: {{cookiecutter.project_name}}

jobs:
  setup-env:
    runs-on: ubuntu-latest
    outputs:
      image-name: {% raw %}${{ steps.setup-docker-image-vars.outputs.image-name }}{% endraw %}
      image-tag: {% raw %}${{ steps.setup-docker-image-vars.outputs.image-tag }}{% endraw %}
      push-image: {% raw %}${{ steps.setup-docker-image-vars.outputs.push-image }}{% endraw %}
      run-test-flag: {% raw %}${{ steps.setup-run-test-vars.outputs.run-test-flag }}{% endraw %}
    steps:
      - id: setup-docker-image-vars
        name: Setup docker image vars
        run: |
          set -eux

          if [[ {% raw %}${{ github.event_name }}{% endraw %} == "workflow_dispatch" ]]; then
              IMAGE_NAME=$BASE_IMAGE_NAME-dev
          else
              IMAGE_NAME=$BASE_IMAGE_NAME
          fi

          if [[ {% raw %}${{ github.event_name }}{% endraw %} == "workflow_dispatch" || ({% raw %}${{ github.event_name }}{% endraw %} == "push" && {% raw %}${{ github.ref }}{% endraw %} == "refs/heads/master") ]]; then
              PUSH_IMAGE=true
          else
              PUSH_IMAGE=false
          fi

          echo "::set-output name=image-name::$IMAGE_NAME"
          echo "::set-output name=image-tag::$GITHUB_SHA"
          echo "::set-output name=push-image::$PUSH_IMAGE"

      - id: setup-run-test-vars
        name: Setup run test vars
        run: |
          set -eux

          if [[ {% raw %}${{ github.event_name }}{% endraw %} == "push" && {% raw %}${{ github.ref }}{% endraw %} == "refs/heads/master" ]]; then
              RUN_TESTS=false
          else
              RUN_TESTS=true
          fi
          echo "::set-output name=run-test-flag::$RUN_TESTS"

  run-ci-tests:
    uses: ./.github/workflows/ci_tests.yaml
    needs: setup-env
    with:
      run-test: {% raw %}${{ needs.setup-env.outputs.run-test-flag}}{% endraw %}

  build-docker:
    uses: ./.github/workflows/build_docker.yaml
    needs:
      - setup-env
      - run-ci-tests
    with:
      image-name: {% raw %}${{ needs.setup-env.outputs.image-name}}{% endraw %}
      image-tag: {% raw %}${{ needs.setup-env.outputs.image-tag}}{% endraw %}
      push-image: {% raw %}${{ needs.setup-env.outputs.push-image}}{% endraw %}
